collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4317043
  brandStrength: 0.4699248
  lightness: 0
  brandColors:
    - '#000000'
    - '#2E2E2E'
  rhythmicContrast: 0.7268171
typography_spectrum: 0.4016291
layout_spectrum: 0.05075188
name: BigThings
